/**
 * Pet Breeds, Services Catalog and Default Recurring Plans for Pet Shop & Veterinary
 */

import { PetService, PetSpecies, PetRecurringPlan } from '../types';

export interface BreedOption {
  id: string;
  name: string;
  species: PetSpecies;
  popularSize?: 'pequeno' | 'medio' | 'grande' | 'gigante';
}

export const PET_SPECIES_LABELS: Record<PetSpecies, { label: string; icon: string }> = {
  cao: { label: 'Cão (Cachorro)', icon: '🐶' },
  gato: { label: 'Gato (Felino)', icon: '🐱' },
  passaro: { label: 'Pássaro (Ave)', icon: '🦜' },
  coelho: { label: 'Coelho', icon: '🐰' },
  roedor: { label: 'Roedor (Hamster/Porquinho)', icon: '🐹' },
  outro: { label: 'Outro Animal', icon: '🐾' },
};

export const PET_BREEDS_BY_SPECIES: Record<PetSpecies, string[]> = {
  cao: [
    'Sem Raça Definida (Vira-lata / SRD)',
    'Shih Tzu',
    'Poodle (Toy / Médio / Gigante)',
    'Golden Retriever',
    'Yorkshire Terrier',
    'Buldogue Francês',
    'Spitz Alemão (Lulu da Pomerânia)',
    'Pastor Alemão',
    'Labrador Retriever',
    'Pug',
    'Rottweiler',
    'Beagle',
    'Dachshund (Teckel / Salsicha)',
    'Border Collie',
    'Maltês',
    'Pinscher Miniatura',
    'Pit Bull / American Bully',
    'Schnauzer Miniatura',
    'Husky Siberiano',
    'Lhasa Apso',
    'Boxer',
    'Cocker Spaniel Inglês',
    'Doberman',
    'Chow Chow',
    'Bernese Mountain Dog',
    'Akita Inu',
    'Terrier Brasileiro (Fox Paulistinha)',
    'Jack Russell Terrier',
    'Chihuahua',
    'Basset Hound',
    'Buldogue Inglês',
    'Dálmata',
    'Cavalier King Charles',
    'Pastor Belga Malinois',
    'Bull Terrier',
    'Shar Pei',
    'Samoieda',
    'Weimaraner',
    'Outra Raça Canina',
  ],

  gato: [
    'Sem Raça Definida (SRD / Vira-lata)',
    'Persa',
    'Siamês',
    'Maine Coon',
    'Angorá Brasileiro / Turco',
    'Sphynx (Sem Pêlo)',
    'Bengal (Gato Leopardo)',
    'Ragdoll',
    'British Shorthair (Inglês)',
    'Siberiano',
    'Azul Russo',
    'Scottish Fold',
    'Gato Exótico (Pelo Curto)',
    'Sagrado da Birmânia',
    'Himalaio',
    'Munchkin (Pernas Curtas)',
    'Burmês',
    'Norueguês da Floresta',
    'American Shorthair',
    'Outra Raça Felina',
  ],

  passaro: [
    'Calopsita',
    'Periquito Australiano',
    'Canário Belga / Canário da Terra',
    'Papagaio Verdadeiro',
    'Caturrita / Ring Neck',
    'Agapornis (Pássaro do Amor)',
    'Cacatua',
    'Manon',
    'Diamante de Gould',
    'Trinca-Ferro',
    'Curió',
    'Coleiro / Coleirinho',
    'Azulão',
    'Calafate',
    'Pardal Doméstico',
    'Pombo / Rolinha',
    'Tucano',
    'Outra Espécie de Ave',
  ],

  coelho: [
    'Mini Lion Head',
    'Holland Lop (Orelha Caída)',
    'Mini Lop',
    'Fuzzy Lop Americano',
    'Nova Zelândia Branco',
    'Angorá Inglês',
    'Hermelin (Polonês)',
    'Chinchila (Coelho)',
    'Gigante de Flandres',
    'Cabeça de Leão',
    'Sem Raça Definida (SRD)',
    'Outra Raça de Coelho',
  ],

  roedor: [
    'Hamster Sírio',
    'Hamster Anão Russo (Winter White)',
    'Hamster Chinês',
    'Porquinho da Índia (Cobaia)',
    'Chinchila Roedora',
    'Gerbil (Esquilo da Mongólia)',
    'Rato Twister (Mecânico / Fancy Rat)',
    'Topolino (Camundongo)',
    'Degu',
    'Outro Roedor',
  ],

  outro: [
    'Furão (Ferret)',
    'Tartaruga / Jabuti',
    'Mini Pig (Mini Porco)',
    'Iguana Verde',
    'Pogona (Dragão Barbudo)',
    'Peixe Ornamental',
    'Outro Pet Não Convencional',
  ],
};

export const DEFAULT_PET_SERVICES: PetService[] = [
  // --- BANHO & TOSA ---
  {
    id: 'srv-banho-simples',
    name: 'Banho Simples Completo',
    category: 'banho_tosa',
    targetSpecies: ['cao', 'gato'],
    price: 45.0,
    priceBySize: {
      pequeno: 45.0,
      medio: 55.0,
      grande: 75.0,
      gigante: 95.0,
    },
    durationMinutes: 45,
    description: 'Shampoo neutro hipoalergênico, condicionador, secagem profissional, escovação e colônia suave.',
    observations: 'Inclui toalha esterilizada individual e algodão protetor auricular.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-banho-tosa-higienica',
    name: 'Banho + Tosa Higiênica',
    category: 'banho_tosa',
    targetSpecies: ['cao', 'gato', 'coelho'],
    price: 65.0,
    priceBySize: {
      pequeno: 65.0,
      medio: 78.0,
      grande: 98.0,
      gigante: 125.0,
    },
    durationMinutes: 60,
    description: 'Banho completo + raspagem higiênica das almofadinhas plantares, barriga e região perianal.',
    observations: 'Recomendado a cada 15 a 30 dias para higiene preventiva.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-tosa-completa-maquina',
    name: 'Tosa Geral na Máquina + Banho',
    category: 'banho_tosa',
    targetSpecies: ['cao', 'gato'],
    price: 85.0,
    priceBySize: {
      pequeno: 85.0,
      medio: 105.0,
      grande: 135.0,
      gigante: 170.0,
    },
    durationMinutes: 75,
    description: 'Tosa completa na máquina com altura de lâmina escolhida pelo tutor + banho finalizador e perfume.',
    observations: 'Ideal para alívio térmico no verão ou pelagens muito densas.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-tosa-tesoura',
    name: 'Tosa Artística na Tesoura + Banho',
    category: 'banho_tosa',
    targetSpecies: ['cao', 'gato'],
    price: 110.0,
    priceBySize: {
      pequeno: 110.0,
      medio: 135.0,
      grande: 175.0,
      gigante: 220.0,
    },
    durationMinutes: 90,
    description: 'Tosa artesanal 100% na tesoura para visual harmônico, elegante e sem marcas de máquina.',
    observations: 'Excelente para Spitz Alemão, Poodle, Yorkshire e Shih Tzu.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-tosa-bebe',
    name: 'Tosa Bebê (Puppy Cut)',
    category: 'banho_tosa',
    targetSpecies: ['cao'],
    price: 95.0,
    priceBySize: {
      pequeno: 95.0,
      medio: 115.0,
      grande: 145.0,
      gigante: 185.0,
    },
    durationMinutes: 80,
    description: 'Pelagem arredondada estilo filhote, corpo em máquina alta e cabeça e patas modeladas na tesoura.',
    observations: 'Mais popular para Shih Tzu, Lhasa Apso e Maltês.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-banho-felino',
    name: 'Banho Especial para Gatos',
    category: 'banho_tosa',
    targetSpecies: ['gato'],
    price: 70.0,
    priceBySize: {
      pequeno: 70.0,
      medio: 85.0,
      grande: 100.0,
    },
    durationMinutes: 60,
    description: 'Banho exclusivo com ambiente silencioso, feromônios calmantes e produtos específicos para felinos.',
    observations: 'Equipe especializada em manejo Cat Friendly sem estresse.',
    isExtraService: false,
    active: true,
  },

  // --- ESTÉTICA & SPA PET ---
  {
    id: 'srv-hidratacao-argan',
    name: 'Hidratação Profunda / Banho de Verniz',
    category: 'estetica',
    targetSpecies: ['cao', 'gato'],
    price: 35.0,
    durationMinutes: 20,
    description: 'Máscara termoativa com óleo de argan, queratina vegetal e aminoácidos para brilho e maciez extrema.',
    observations: 'Fecha cutículas e previne formação de nós.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-desembolo-pelos',
    name: 'Desembolo e Remoção de Nós',
    category: 'estetica',
    targetSpecies: ['cao', 'gato'],
    price: 30.0,
    durationMinutes: 30,
    description: 'Desembaraço cuidadoso com fluído desemborrachante sem quebrar ou danificar os fios.',
    observations: 'Cobrado por sessão/tempo dependendo da complexidade.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-remocao-subpelo',
    name: 'Remoção de Subpelo (Carda / Furminator)',
    category: 'estetica',
    targetSpecies: ['cao', 'gato', 'coelho'],
    price: 28.0,
    durationMinutes: 25,
    description: 'Eliminação profunda de pelos mortos presos no subpelo. Reduz em até 90% a queda de pelos em casa.',
    observations: 'Indispensável para Golden Retriever, Pastor Alemão, Husky e Gatos.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-banho-medicamentoso',
    name: 'Banho Medicamentoso / Terapêutico',
    category: 'estetica',
    targetSpecies: ['cao', 'gato'],
    price: 30.0,
    durationMinutes: 20,
    description: 'Aplicação de shampoo prescrito pelo veterinário (clorexidina, cetoconazol, peróxido ou calmante dérmico).',
    observations: 'Necessário respeitar tempo de pausa de 10 a 15 minutos do medicamento na pele.',
    isExtraService: true,
    active: true,
  },

  // --- SERVIÇOS EXTRAS / ADICIONAIS ---
  {
    id: 'srv-corte-unhas',
    name: 'Corte e Lixamento de Unhas',
    category: 'outros',
    targetSpecies: ['cao', 'gato', 'passaro', 'coelho', 'roedor'],
    price: 15.0,
    durationMinutes: 15,
    description: 'Corte anatômico de unhas com alicate profissional e hemostático preventivo de sangramento.',
    observations: 'Evita dores nas articulações e encravamento de unhas.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-limpeza-ouvidos',
    name: 'Limpeza e Higiene Auricular (Ouvidos)',
    category: 'outros',
    targetSpecies: ['cao', 'gato', 'coelho'],
    price: 15.0,
    durationMinutes: 15,
    description: 'Higienização suave do conduto auditivo com solução ceruminolítica e remoção de excesso de pelos.',
    observations: 'Previne otites fúngicas e bacterianas.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-escovacao-dental',
    name: 'Escovação Dentária com Gel Enzimático',
    category: 'outros',
    targetSpecies: ['cao', 'gato'],
    price: 20.0,
    durationMinutes: 15,
    description: 'Escovação bucal com pasta enzimática com sabor de carne/frango que combate placa e mau hálito.',
    observations: 'Acompanha escova massageadora.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-antipulgas-aplicacao',
    name: 'Aplicação de Pipeta / Antipulgas',
    category: 'outros',
    targetSpecies: ['cao', 'gato'],
    price: 25.0,
    durationMinutes: 10,
    description: 'Aplicação correta de medicamento contra pulgas, carrapatos e mosquitos transmissores de leishmaniose.',
    observations: 'Não inclui o frasco do medicamento ou comprimido.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-lacos-aderecos',
    name: 'Kit Laços, Gravatas & Bandanas Luxo',
    category: 'estetica',
    targetSpecies: ['cao', 'gato'],
    price: 10.0,
    durationMinutes: 5,
    description: 'Enfeites artesanais, gravatinhas temáticas ou bandanas temáticas personalizadas.',
    observations: 'Aderência macia e segura para a pele do pet.',
    isExtraService: true,
    active: true,
  },

  // --- SERVIÇOS VETERINÁRIOS & CLÍNICA ---
  {
    id: 'srv-consulta-veterinaria',
    name: 'Consulta Clínica Veterinária Geral',
    category: 'veterinario',
    targetSpecies: ['cao', 'gato', 'passaro', 'coelho', 'roedor', 'outro'],
    price: 130.0,
    durationMinutes: 45,
    description: 'Avaliação clínica completa: ausculta cardíaca/pulmonar, palpação abdominal, mucosa, peso, dentes e temperatura.',
    observations: 'Dá direito a 1 retorno em até 30 dias se necessário.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-consulta-retorno',
    name: 'Consulta de Retorno Clínico',
    category: 'veterinario',
    targetSpecies: ['cao', 'gato'],
    price: 0.0,
    durationMinutes: 25,
    description: 'Reavaliação pós-tratamento ou pós-exames laboratoriais.',
    observations: 'Válido conforme regras da clínica.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-vacina-v10',
    name: 'Vacinação Polivalente V10 / V8 Canina',
    category: 'veterinario',
    targetSpecies: ['cao'],
    price: 95.0,
    durationMinutes: 20,
    description: 'Imunização contra Cinomose, Parvovirose, Hepatite, Leptospirose (4 sorovares) e Coronavirose.',
    observations: 'Inclui exame prévio de aptidão à vacinação e carimbo na carteirinha.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-vacina-antirrabica',
    name: 'Vacinação Antirrábica (Cães e Gatos)',
    category: 'veterinario',
    targetSpecies: ['cao', 'gato'],
    price: 75.0,
    durationMinutes: 15,
    description: 'Proteção contra o vírus da Raiva, obrigatória por lei e essencial para a saúde pública.',
    observations: 'Reforço anual recomendado.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-vacina-gato-quintupla',
    name: 'Vacinação Quíntupla Felina (V5)',
    category: 'veterinario',
    targetSpecies: ['gato'],
    price: 110.0,
    durationMinutes: 20,
    description: 'Proteção contra Panleucopenia, Rinotraqueíte, Calicivirose, Clamidiose e Leucemia Felina (FeLV).',
    observations: 'Exige teste FeLV negativo prévio para novos animais.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-microchipagem',
    name: 'Microchipagem com Cadastro Nacional',
    category: 'veterinario',
    targetSpecies: ['cao', 'gato', 'passaro', 'outro'],
    price: 120.0,
    durationMinutes: 20,
    description: 'Implantação indolor de microchip ISO 11784/11785 sob a pele para identificação definitiva do pet.',
    observations: 'Inclui certificado internacional e registro no banco de dados.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-vermifugacao-oral',
    name: 'Vermifugação com Dose Prescrita',
    category: 'veterinario',
    targetSpecies: ['cao', 'gato', 'coelho', 'roedor'],
    price: 25.0,
    durationMinutes: 10,
    description: 'Administração de vermífugo de amplo espectro para parasitas redondos e chatos (giárdia e vermes intestinais).',
    observations: 'Dose calculada rigorosamente por quilograma de peso vivo.',
    isExtraService: true,
    active: true,
  },

  // --- TRANSPORTE TÁXI DOG ---
  {
    id: 'srv-taxi-dog-ida-volta',
    name: 'Táxi Dog Leva e Traz (Ida e Volta)',
    category: 'transporte',
    targetSpecies: ['cao', 'gato', 'coelho'],
    price: 35.0,
    durationMinutes: 30,
    description: 'Transporte climatizado, seguro com cinto peitoral e caixas de transporte higienizadas da casa do tutor até o pet shop e retorno.',
    observations: 'Valor para raio padrão de até 5km.',
    isExtraService: true,
    active: true,
  },
  {
    id: 'srv-taxi-dog-somente-ida',
    name: 'Táxi Dog (Somente Ida ou Somente Volta)',
    category: 'transporte',
    targetSpecies: ['cao', 'gato'],
    price: 20.0,
    durationMinutes: 20,
    description: 'Transporte seguro de 1 trecho.',
    observations: 'Agendamento prévio com motorista.',
    isExtraService: true,
    active: true,
  },

  // --- HOTEL & DAYCARE CRECHE ---
  {
    id: 'srv-diaria-daycare',
    name: 'Diária de Creche / Daycare Pet (Recreação)',
    category: 'hotel_creche',
    targetSpecies: ['cao'],
    price: 60.0,
    durationMinutes: 480,
    description: 'Socialização monitorada por monitores, brincadeiras educativas, enriquecimento ambiental e descanso.',
    observations: 'Horário das 08h às 18h.',
    isExtraService: false,
    active: true,
  },
  {
    id: 'srv-diaria-hotel',
    name: 'Diária de Hotelzinho Pet (Pernoite)',
    category: 'hotel_creche',
    targetSpecies: ['cao', 'gato'],
    price: 90.0,
    durationMinutes: 1440,
    description: 'Hospedagem com acompanhamento 24h, suítes individuais climatizadas e envio diário de fotos e vídeos no WhatsApp.',
    observations: 'Check-in e check-out às 12h.',
    isExtraService: false,
    active: true,
  },
];

export const DEFAULT_RECURRING_PLANS: PetRecurringPlan[] = [
  {
    id: 'pln-mensal-4-banhos',
    code: '#PLN-101',
    clientId: 'cli-1',
    clientName: 'Ana Clara Albuquerque',
    clientPhone: '(11) 98765-4321',
    petId: 'pet-1',
    petName: 'Mel',
    petBreed: 'Shih Tzu',
    petSpecies: 'cao',
    planType: 'mensal',
    frequency: 'mensal',
    name: 'Plano Mensal - 4 Banhos (1 por semana) + Tosa Higiênica',
    planName: 'Plano Mensal - 4 Banhos (1 por semana) + Tosa Higiênica',
    servicesIncluded: ['Banho Completo (4x)', 'Tosa Higiênica (1x)', 'Corte de Unhas Grátis'],
    totalSessions: 4,
    usedSessions: 2,
    price: 180.0,
    billingDay: 10,
    startDate: '2026-09-01',
    nextBillingDate: '2026-10-10',
    paymentStatus: 'pago',
    active: true,
    notes: 'Cliente prefere perfume suave de lavanda.',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'pln-quinzenal-2-banhos',
    code: '#PLN-102',
    clientId: 'cli-2',
    clientName: 'Carlos Eduardo Mendes',
    clientPhone: '(11) 99876-5432',
    petId: 'pet-2',
    petName: 'Thor',
    petBreed: 'Golden Retriever',
    petSpecies: 'cao',
    planType: 'quinzenal',
    frequency: 'quinzenal',
    name: 'Plano Quinzenal - 2 Banhos + Remoção de Subpelo',
    planName: 'Plano Quinzenal - 2 Banhos + Remoção de Subpelo',
    servicesIncluded: ['Banho Porte Grande (2x)', 'Remoção de Subpelo com Furminator'],
    totalSessions: 2,
    usedSessions: 1,
    price: 150.0,
    billingDay: 15,
    startDate: '2026-09-01',
    nextBillingDate: '2026-09-15',
    paymentStatus: 'em_dia',
    active: true,
    notes: 'Secagem cuidadosa nas orelhas.',
    createdAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'pln-mensal-felino',
    code: '#PLN-103',
    clientId: 'cli-3',
    clientName: 'Mariana Souza Lima',
    clientPhone: '(11) 97654-3210',
    petId: 'pet-3',
    petName: 'Simba',
    petBreed: 'Persa',
    petSpecies: 'gato',
    planType: 'mensal',
    frequency: 'mensal',
    name: 'Plano Mensal Felino - 2 Banhos Calmantes + Desembolo',
    planName: 'Plano Mensal Felino - 2 Banhos Calmantes + Desembolo',
    servicesIncluded: ['Banho Cat Friendly (2x)', 'Desembolo de Pelos', 'Corte de Unhas'],
    totalSessions: 2,
    usedSessions: 0,
    price: 140.0,
    billingDay: 5,
    startDate: '2026-09-05',
    nextBillingDate: '2026-10-05',
    paymentStatus: 'em_dia',
    active: true,
    notes: 'Gato idoso, manejo super tranquilo.',
    createdAt: '2026-09-05T09:15:00Z',
  },
];
